server:
  port: 8090
logging:
  path: E:/Project/IdeaProject/etherRTC/logs
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  datasource:
    username: root
    password: qaz1230+-
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver