server:
  port: 8090
logging:
  path: E:/Project/IdeaProject/etherRTC/logs
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .html
    static-path-pattern: /**
  datasource:
    username: root
    password: qaz1230+-
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 10000